export default [
  {
    description: "Salário",
    amount: "1300.52",
    type: "entrada",
    frequency: "recorrente",
    date: "2025-01-10",
  },
  {
    description: "Freela",
    amount: "150.13",
    type: "entrada",
    frequency: "eventual",
    date: "2025-01-17",
  },
  {
    description: "Salário",
    amount: "2500.23",
    type: "entrada",
    frequency: "recorrente",
    date: "2025-02-10",
  },
  {
    description: "Freela site",
    amount: "900.23",
    type: "entrada",
    frequency: "eventual",
    date: "2025-02-21",
  },
  {
    description: "Freela app",
    amount: "950.92",
    type: "entrada",
    frequency: "eventual",
    date: "2025-02-23",
  },
  {
    description: "Salário",
    amount: "2500.25",
    type: "entrada",
    frequency: "recorrente",
    date: "2025-03-10",
  },
  {
    description: "Salário",
    amount: "2500.18",
    type: "entrada",
    frequency: "recorrente",
    date: "2025-04-10",
  },
  {
    description: "Salário",
    amount: "2500.15",
    type: "entrada",
    frequency: "recorrente",
    date: "2025-05-10",
  },
  {
    description: "Salário",
    amount: "2500.12",
    type: "entrada",
    frequency: "recorrente",
    date: "2025-06-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2025-07-10",
  },
  {
    description: "Salário",
    amount: "2500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2025-08-10",
  },

  {
    description: "Salário",
    amount: "4500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2024-11-05",
  },

  {
    description: "Salário",
    amount: "4500.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2024-12-05",
  },
  {
    description: "Freelance - Web Design",
    amount: "800.00",
    type: "entrada",
    frequency: "eventual",
    date: "2024-12-10",
  },
  {
    description: "Décimo terceiro salário",
    amount: "4500.00",
    type: "entrada",
    frequency: "eventual",
    date: "2024-12-15",
  },
  {
    description: "Venda de itens usados",
    amount: "350.00",
    type: "entrada",
    frequency: "eventual",
    date: "2024-12-18",
  },
  {
    description: "Cashback do cartão",
    amount: "50.00",
    type: "entrada",
    frequency: "eventual",
    date: "2024-12-22",
  },
  {
    description: "Rendimento de investimento",
    amount: "220.00",
    type: "entrada",
    frequency: "recorrente",
    date: "2024-12-25",
  },
];
